# 注册
POST http://localhost:8081/api/rest/auth/user/register
Content-Type: application/json

{
  "userName": " qinyu",
  "password": "123456"
}

###

# 登录
POST http://localhost:8081/api/rest/auth/user/login
Content-Type: application/json

{
  "userName": "qinyu",
  "password": "123456"
}

###

# 自动登录
POST http://localhost:8081/api/rest/auth/user/auto-login
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxaW55dSIsImV4cCI6MTU3OTkyNjA0NSwiaWF0IjoxNTc5MzIxMjQ1fQ.mMGaosi1q4Z-yTM9CJiO6fo5LMENyeXnq7s5xr6vDx4bNkr9ITUuvMrn7cpaUZzVPFDkXcxPr6wJQ-UcluneXw

###

# 获取用户信息
GET http://localhost:8081/api/userinfo
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxaW55dSIsImV4cCI6MTU3OTkyNjA0NSwiaWF0IjoxNTc5MzIxMjQ1fQ.mMGaosi1q4Z-yTM9CJiO6fo5LMENyeXnq7s5xr6vDx4bNkr9ITUuvMrn7cpaUZzVPFDkXcxPr6wJQ-UcluneXw

###

# 创建课程
POST http://localhost:8081/api/course
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxaW55dSIsImV4cCI6MTU3OTkyNjA0NSwiaWF0IjoxNTc5MzIxMjQ1fQ.mMGaosi1q4Z-yTM9CJiO6fo5LMENyeXnq7s5xr6vDx4bNkr9ITUuvMrn7cpaUZzVPFDkXcxPr6wJQ-UcluneXw
Content-Type: application/json

{
  "title": "CAC管理教练特种兵计划",
  "description": "CAC管理教练特种兵计划日常作业",
  "questions": [
    {"title":"《敏捷教练培养的“守、破、离”》读后感​"},
    {"title":"《培养“教练团队”为什么是敏捷转型中的必经之路》读后感"},
    {"title":"文化轰炸"},
    {"title":"站会总有人迟到怎么破？"},
    {"title":"文化解读之“求责于己”实例化"},
    {"title":"结合实践案例分享需求梳理过程中遇到的困难和解决方案"},
    {"title":"《Scrum看板相得益彰》读书笔记"},
    {"title":"《Scrum精髓》读书笔记"},
    {"title":"深度思考：如何提高质量"},
    {"title":"AC验收条件作业分享"},
    {"title":"《如何构建敏捷项目管理团队》读书笔记"},
    {"title":"关于“度量”"},
    {"title":"STAR模型"}
  ],
  "creator":{
    "id": "f838106d-3f9a-4107-a605-7e6d90b18e98"
  }
}

###

# 获取课程列表
GET http://localhost:8081/api/course
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxaW55dSIsImV4cCI6MTU3OTkyNjA0NSwiaWF0IjoxNTc5MzIxMjQ1fQ.mMGaosi1q4Z-yTM9CJiO6fo5LMENyeXnq7s5xr6vDx4bNkr9ITUuvMrn7cpaUZzVPFDkXcxPr6wJQ-UcluneXw

###

# 删除课程
DELETE http://localhost:8081/api/course?courseId=24246584-da8c-4331-9f1a-29c5f549a932
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxaW55dSIsImV4cCI6MTU3OTkyNjA0NSwiaWF0IjoxNTc5MzIxMjQ1fQ.mMGaosi1q4Z-yTM9CJiO6fo5LMENyeXnq7s5xr6vDx4bNkr9ITUuvMrn7cpaUZzVPFDkXcxPr6wJQ-UcluneXw
###

# 订阅课程
POST http://localhost:8081/api/subscription?courseId=f9f7707f-fb06-46dd-ba78-ebcb1e990581
userId: 58a75ee9-8ebf-4ec3-8f4e-3bf60846272d
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxaW55dSIsImV4cCI6MTU3OTkyNjA0NSwiaWF0IjoxNTc5MzIxMjQ1fQ.mMGaosi1q4Z-yTM9CJiO6fo5LMENyeXnq7s5xr6vDx4bNkr9ITUuvMrn7cpaUZzVPFDkXcxPr6wJQ-UcluneXw

###

# Creator 不能订阅自己的课程
POST http://localhost:8081/api/subscription?courseId=f9f7707f-fb06-46dd-ba78-ebcb1e990581
userId: f838106d-3f9a-4107-a605-7e6d90b18e98
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxaW55dSIsImV4cCI6MTU3OTkyNjA0NSwiaWF0IjoxNTc5MzIxMjQ1fQ.mMGaosi1q4Z-yTM9CJiO6fo5LMENyeXnq7s5xr6vDx4bNkr9ITUuvMrn7cpaUZzVPFDkXcxPr6wJQ-UcluneXw

###

# CourseID 不存在
POST http://localhost:8081/api/subscription?courseId=f9f7707f-fb06-46dd-ba78-ebcb1e990582
userId: 58a75ee9-8ebf-4ec3-8f4e-3bf60846272d
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxaW55dSIsImV4cCI6MTU3OTkyNjA0NSwiaWF0IjoxNTc5MzIxMjQ1fQ.mMGaosi1q4Z-yTM9CJiO6fo5LMENyeXnq7s5xr6vDx4bNkr9ITUuvMrn7cpaUZzVPFDkXcxPr6wJQ-UcluneXw

###